// Generated by CoffeeScript 1.6.3
(function() {
  var FS, Q, USAGE, argv, batchUp, partition, regionFilePattern, _,
    _this = this;

  FS = require("q-io/fs");

  Q = require("q");

  _ = require("underscore")._;

  argv = require('optimist').argv;

  USAGE = "USAGE: " + process.argv[0] + " " + process.argv[1] + " --dir <directory to process> --out <file to output time series in>";

  if (!((argv.dir != null) && argv.out)) {
    console.error(USAGE);
    process.exit(1);
  }

  partition = function(partitionSize) {
    return function(list) {
      var groups;
      groups = _.groupBy(list, function(value, index) {
        return Math.floor(index / partitionSize);
      });
      return _.map(groups, function(value) {
        return value;
      });
    };
  };

  batchUp = partition(100);

  regionFilePattern = /.+(\d+)\/regions$/;

  FS.listTree(argv.dir).then(function(entries) {
    var batches, dispatchBatch, reads, regionFileNames;
    regionFileNames = _.filter(entries, function(e) {
      return regionFilePattern.test(e);
    });
    batches = batchUp(regionFileNames);
    console.log("Files to read: " + regionFileNames.length);
    console.log("Batches: " + batches.length);
    reads = function(fileNames) {
      return _.map(fileNames, function(f) {
        return FS.read(f).then(function(content) {
          return {
            name: f,
            content: content
          };
        });
      });
    };
    dispatchBatch = function(index, batches) {
      var batch;
      if (index < batches.length) {
        batch = batches[index];
        console.log("Doing batch " + index + " of length " + batch.length);
        return Q.all(reads(batch)).then(function(read) {
          return dispatchBatch(index + 1, batches);
        }, function(error) {
          return console.error(error);
        });
      }
    };
    return dispatchBatch(0, batches);
  });

}).call(this);

/*
//@ sourceMappingURL=extractTimeSeries.map
*/
